### ISSUE TITLE
AppHDA

### ISSUE THREAD

**Issue by tranquanghuy1612** [ngoctp/clover-uefi-hp-folio-9470m-1600x900#1]
Em dùng máy HP9470M res 1600x900 i5 3437U
copy EFI của bác vô nhưng có AppleHDA là không nhận. Bác có thể trợ giúp em được không.
À còn video khi xem youtube , tua video nó k load dc, facebook k load được video.
HD4000 nhận đủ vram. thank bác!

**Comment by ngoctp** [comment]
Em tải Kext Wizard về cài "CodecCommander.kext", "DummyHDA.kext" trong thư mục kexts vào máy, sau đó rebuild cache và repair permissions nhé.
Vụ video thì anh không biết, cái đấy chắc do phần mềm hoặc lỗi mạng thôi.
Anh dùng AppleHDA thỉnh thoảng shutdown/restart lại bị máy đơ, không nhận audio, em chạy thử xem có bị không.

**Comment by tranquanghuy1612** [comment]
em đã cài 2 kext đó bằng kext wizard , và rebuild cache, repair permissons luôn. khởi động laiuj máy vẫn không có lên âm thanh a ạ.
trong clover phần device có inject layout không anh.
à vụ video e chuyển sang chrome thì chạy ok không bị nữa. safari mới bị
anh có facebook không ạ.

**Comment by ngoctp** [comment]
ngày trước có cái AppleHDADisabler.kext, em tìm trong máy xem có cái kext đó không, xóa nó đi!
em có sử dụng config.plist của anh không?
Phần layout của anh thế này:
![image](https://user-images.githubusercontent.com/4251459/40686691-6c918684-63c2-11e8-9041-f7443201af70.png)

**Comment by tranquanghuy1612** [comment]
e vừa kiểm tra nhưng không thấy kext đó
em dùng nguyên cái EFI của anh luôn.
mà anh có bản img dùng cho r-drive không :D 
Hiện tại e đang dùng tmaj voodoo . cắm tai thì dùng ngon, loa ngoài bé tiu ti :v

**Comment by tranquanghuy1612** [comment]
em đã patch dc rồi.
e vào patch lại trong DSDT layout 12, inject clover nữa. lên luôn

**Comment by tranquanghuy1612** [comment]
ôi thank anh nhiều nhé.
em patch dc AppleHDA rồi. patch lại trong DSDT lauout 12 và inject trong
clover thôia a ạ. nhận oke rồi. thank anh nhé giờ em mới check mail

2018-05-30 5:34 GMT+08:00 Ngoc P. Tran <notifications@github.com>:
